### ISSUE TITLE
NOT DEPLOYING 

### ISSUE THREAD

**Issue by Divytech** [itzAsuraa/ResponseByAi#6]
showing this error ```2024-12-14 18:43:29,122 - pyrogram.dispatcher - ERROR - Telegram says: [400 CHANNEL_INVALID] (caused by "channels.GetChannels") Pyrogram 2.3.52 thinks: The channel parameter is invalid
Traceback (most recent call last):
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 63, in resolve_peer
    return await self.storage.get_peer_by_id(peer_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/pyrogram/storage/sqlite_storage.py", line 210, in get_peer_by_id
    raise KeyError(f"ID not found: {peer_id}")
KeyError: 'ID not found: -1001734958816'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/opt/render/project/src/plugins/main.py", line 10, in start_command
    if FSUB and not await get_fsub(client, message):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/database/fsub.py", line 13, in get_fsub
    await bot.get_chat_member(target_channel_id, user_id)
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/pyrogram/methods/chats/get_chat_member.py", line 58, in get_chat_member
    chat = await self.resolve_peer(chat_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 113, in resolve_peer
    await self.invoke(
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ChannelInvalid: Telegram says: [400 CHANNEL_INVALID] (caused by "channels.GetChannels") Pyrogram 2.3.52 thinks: The channel parameter is invalid``` 

when try to host on render and double checked channel id is valid and bot is in channel with admin previlage

**Comment by CodeSearchDev** [comment]
Add your channel id in .env

**Comment by Divytech** [comment]
still same even adding in .env file the result is same peer_id is invailid
` pyrogram.dispatcher - ERROR - Telegram says: [400 CHANNEL_INVALID] (caused by "channels.GetChannels") Pyrogram 2.3.52 thinks: The channel parameter is invalid
Traceback (most recent call last):
  File "C:\Users\Divyansh\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\methods\advanced\resolve_peer.py", line 63, in resolve_peer
    return await self.storage.get_peer_by_id(peer_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Divyansh\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\storage\sqlite_storage.py", line 210, in get_peer_by_id
    raise KeyError(f"ID not found: {peer_id}")
KeyError: 'ID not found: -1002359608571'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Divyansh\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\Divyansh\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\handlers\message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "D:\BOT\ResponseByAi\plugins\main.py", line 10, in start_command
    if FSUB and not await get_fsub(client, message):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\BOT\ResponseByAi\database\fsub.py", line 10, in get_fsub
    await bot.get_chat_member(target_channel_id, user_id)
  File "C:\Users\Divyansh\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\methods\chats\get_chat_member.py", line 58, in get_chat_member
    chat = await self.resolve_peer(chat_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Divyansh\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\methods\advanced\resolve_peer.py", line 113, in resolve_peer
    await self.invoke(
  File "C:\Users\Divyansh\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\methods\advanced\invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Divyansh\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\session\session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Divyansh\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\session\session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "C:\Users\Divyansh\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\errors\rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ChannelInvalid: Telegram says: [400 CHANNEL_INVALID] (caused by "channels.GetChannels") Pyrogram 2.3.52 thinks: The channel parameter is invalid
2024-12-15 11:14:15,117 - pyrogram.dispatcher - ERROR - Telegram says: [400 CHANNEL_INVALID] (caused by "channels.GetChannels") Pyrogram 2.3.52 thinks: The channel parameter is invalid
Traceback (most recent call last):
  File "C:\Users\Divyansh\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\methods\advanced\resolve_peer.py", line 63, in resolve_peer
    return await self.storage.get_peer_by_id(peer_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Divyansh\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\storage\sqlite_storage.py", line 210, in get_peer_by_id
    raise KeyError(f"ID not found: {peer_id}")
KeyError: 'ID not found: -1002359608571'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Divyansh\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\Divyansh\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\handlers\message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "D:\BOT\ResponseByAi\plugins\main.py", line 10, in start_command
    if FSUB and not await get_fsub(client, message):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\BOT\ResponseByAi\database\fsub.py", line 10, in get_fsub
    await bot.get_chat_member(target_channel_id, user_id)
  File "C:\Users\Divyansh\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\methods\chats\get_chat_member.py", line 58, in get_chat_member
    chat = await self.resolve_peer(chat_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Divyansh\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\methods\advanced\resolve_peer.py", line 113, in resolve_peer
    await self.invoke(
  File "C:\Users\Divyansh\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\methods\advanced\invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Divyansh\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\session\session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Divyansh\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\session\session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "C:\Users\Divyansh\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\errors\rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ChannelInvalid: Telegram says: [400 CHANNEL_INVALID] (caused by "channels.GetChannels") Pyrogram 2.3.52 thinks: The channel parameter is invalid`

**Comment by itzAsuraa** [comment]
raise KeyError(f"ID not found: {peer_id}")
KeyError: 'ID not found: -1002359608571'

Adding bot on your channel or check channel id
